### ISSUE TITLE
User Initiated Transactions Proposal

### ISSUE THREAD

**Issue by orlax** [fiatconnect/specification#93]
In the case of Latin American Countries, it is not possible to withdraw or debit money from an account using the ACH banking APIs. This means that for Transfers In we need the ability to have "User Initiated transactions" where users actively send the money from their bank accounts to the CICO provider. This is normally handled by country wide systems. For example in the case of Colombia it is PSE https://www.pse.com.co/persona

So, for a full description of the problem lets go to this document: https://www.notion.so/orlagames/User-Initiated-Transactions-and-Cash-Payments-proposal-03f8234f4fc14e749a9cb047e1557cc5?pvs=4

once you have read that, here is our current solution: 

- On the transfer in endpoint, things remain the same, we receive the pre-registered Fiat account ID and quote ID: 
`{
	"FiatAccountId":"987002",
   "QuoteID":"acb34623"
}`
- Next CICO providers that need to use this user initiated transactions would use the account information and user information obtained in the KYC process to create the payment intention in the country banking payment provider. 
- on the response object we would return the URL were payment needs to be completed: 
```
{
	transferId: `string`,
	transferStatus: `WaitingForPayment`,
	transferAddress: `CELO Address`, 
	transferDetails: '{method:"PSE", url:"some_url"}'
}
```
By introducing that new transferDetails field, the intention is to have some schemas where we can provide the URLs and the system name being used to procesate payment. Then users can go to that url and complete payment on their own, to mark the transaction as user initiated we can use a new "transferStatus" that states we are waiting for the user to complete the transaction. In this case the clients can check for this status and redirect users to the proper URL so that they can complete payment. 

In this video I talk about the problem and do a mini demo of the flow: 
https://drive.google.com/file/d/1AcMmx5r6dKDnNRWinEBxr6nrNo6mQLeS/view?usp=sharing

so, all in all I think if we agree on the new status and what that transferDetails would look like this could be a minor adition to the spec. 

Let's discuss!

**Comment by 0xtuytuy** [comment]
This is a good start @orlax I think however this is quite specific to LATAM.

If we wanted to make his more generic to cover the rest of the world where user-initiated payments are important I would do the following modifications.

I would keep the `transferDetails` key in the response of the `POST` `transfer/in` endpoint as you suggest, but I would take the `method` key that you are proposing out of the object, this would therefore allow the devs to see without going too much down the tree what schema they can expect in the `transferDetails` key
```
{
	transferId: `string`,
	transferStatus: `WaitingForPayment`,
	transferAddress: `CELO Address`, 
        transferMethod: enum of TransferType
	transferDetails: transferDetailsSchema
}
```

But in the `transferDetails` I would allow for different schemas, here are 2 examples that I think would cover your use case and one in Europe using the Faster Payment rails of the UK and the normal IBAN/BIC payment rails of the EU. Something else to consider is some of these payment methods (for example the UK one with Faster Payment Rails) will require the user to have done some KYC, these are requirements imposed by the banking institutions in the respective regions.

LATAM Schema:
```
{
        url:"some_url"
}
```

EU Schema:
```
{
        ibanNumber: STRING following the standard defined here: https://www.iban.com/structure
        bicNumber?: STRING following the standard defined here: https://www.swift.com/standards/data-standards/bic-business-identifier-code
        kycRequired: boolean
}
```

UK Schema:
```
{
        accountNumber: STRING of the format explained here: https://www.starlingbank.com/resources/banking/bank-accounts-explained-sort-code-account-number/#:~:text=In%20the%20UK%2C%20most%20bank,conjunction%20with%20a%20sort%20code.
        sortCode: STRING of the format explained here: https://www.starlingbank.com/resources/banking/bank-accounts-explained-sort-code-account-number/#:~:text=In%20the%20UK%2C%20most%20bank,conjunction%20with%20a%20sort%20code.
        kycRequired: boolean
}
```

**Comment by 0xtuytuy** [comment]
This is a good start @orlax I think however this is quite specific to LATAM.

If we wanted to make this more generic to cover the rest of the world where user-initiated payments are the only option or at least important I would do the following modifications.

I would keep the `transferDetails` Object in the `200` `POST` `/transfer/in` as you suggest, but I would put the `method` key that you are proposing in the request body of `POST` `/quote/in`. 

The reason for this is some Payment methods will carry different costs, and different KYC levels and CICOs might support  multiple options (for example in Europe the partner/end-user could decide to user SEPA which is longer but cheap rather then Instant SEPA which is instant but more expensive)

**I would therefore have the `200` `POST` `/transfer/in` modified as follow:**

```
{
	transferId: `string`,
	transferStatus: `WaitingForPayment`,
	transferAddress: `CELO Address`, 
	transferDetails?: transferDetailsSchema
}
```

here are 2 examples that I think would cover your use case and Europe/UK using the Faster Payment rails and SEPA IBAN/BIC payment rails.

LATAM Schema:
```
{
        url:"some_url"
}
```

EU Schema:
```
{
        ibanNumber: STRING following the standard defined here: https://www.iban.com/structure
        bicNumber?: STRING following the standard defined here: https://www.swift.com/standards/data-standards/bic-business-identifier-code
}
```

UK Schema:
```
{
        accountNumber: STRING of the format explained here: https://www.starlingbank.com/resources/banking/bank-accounts-explained-sort-code-account-number/#:~:text=In%20the%20UK%2C%20most%20bank,conjunction%20with%20a%20sort%20code.
        sortCode: STRING of the format explained here: https://www.starlingbank.com/resources/banking/bank-accounts-explained-sort-code-account-number/#:~:text=In%20the%20UK%2C%20most%20bank,conjunction%20with%20a%20sort%20code.
}
```

**I would also suggest modifying `POST` `/quote/in`as follow:**

For the body:
- `transferType`: {`TransferTypeEnum`} [REQUIRED]
  - The desired transfer type to use for a transfer in the quote; is selected from a predefined list of transfer types supported by FiatConnect.

We would therefore need to add a `TransferTypeEnum` as well, I think a good start is:
```
[
  `FSP`, //Faster Payments for the UK (using Account Number and Sort Code)
  `SEPA`, //EU standard IBAN enabled transfers
  `ISEPA`, //EU instant IBAN enabled transfers
  `PSE`,//LATAM standard (@orlax can help define this)
  `ACHPULL`,//USA Standard
  `CC`,//Credit card
]
```

It will therefore be the CICO provider's responsibility to:
1. make sure they support the desired `transferType` and response an error code if not
2. make sure the KYC requirements in the response of `200` `/quote/in` fit with the requested payment type
3. make sure that the `transferDetails` of the `200` `/transfer/in` also matches the requested `transferType` in `200` `/quote/in`

**Comment by 0xtuytuy** [comment]
Hey @orlax I hear you, but I think that is just what we have to deal with. 

I-SEPA (Instant SEPA) and SEPA (the old version) have a 50% difference in cost for example, it's far to be the same system, SEPA can also take up to 3 days, while I-SEPA is always instant. There are lots of distinctions. 

I can give you other examples with Mobile Money providers in Africa for example, all have very different requirements as well. I know we might end up with a very long list but I think we don't really have a choice, it's like saying we can shorten `FiatTypeEnum`, not really doable...

**Comment by jophish** [comment]
Some more focused thoughts after discussing this for a while with @cajubelt:

First, @0xtuytuy, while the issue of "underlying transfer methods" does seem to be relevant, it seems orthogonal to the issue of user-initiated transfers. These "underlying methods" for payment do not necessarily apply _only_ to user-initiated transfers; they could apply to non-user-initiated cash-ins, or even cash-outs. For this reason, and since solving this problem would require a relatively large change to the spec, I think this should be addressed separately from supporting user-initiated transfers. We welcome a PR on the specification, or a separate proposal to solve this issue, but I think it should be decoupled from solving the problem at hand. For the time being, we recommend that providers just pick _one_ underlying transfer method, rather than giving the user a choice between several.

@orlax, after some thought, we realized that supporting user-initiated cash-ins will _also_ require some changes to the `quote/in` endpoint. In short, if a client doesn't support user-initiated cash-ins, it needs to know if a quote _requires_ user-initiation _at the time of getting the quote_, so it can ignore the quote and ensure nothing breaks down the line when initiating the transfer itself.

To that end, a high-level overview of the proposed flow for user-initiated cash-ins would be as follows:
* Client requests a quote from `/quote/in`
* Provider returns quote; for each `FiatAccountSchema` that requires some form of user-initiated action, a, e.g., `userActionType` field is returned alongside the rest of the Fiat Account schema data. This `userActionType` will be an enum, signifying the _type_ of user action required.
* Client provides Fiat Account info, KYC, etc., if not already on file
* Client initiates the transfer by posting to `/transfer/in`
* Provider returns regular transfer info, with an additional, e.g., `userActionDetails` field. This `userActionDetails` field will have a _different_ schema depending on the `userActionType` associated with the `FiatAccountSchema` the user selected, as determined by the quote.
  * `userActionDetails` will contain the relevant data required by the user in order to initiate the transfer in on their end. Since the client knows the `userActionType` already, it can use `userActionType` to infer the semantics of the data in `userActionDetails`, and render a different UI depending on its value. (e.g., for `userActionType='PSE'`, we just render a link with some instructions).

Does this make sense? Curious to hear your thoughts on this.

**Comment by ailsoncgt** [comment]
> Does this make sense? Curious to hear your thoughts on this.

Here for us(Brazil), seems consistent with the needs of the PIX copy and paste.
```
{
	"transferId": `2b2972a6-49e2-49d0-9e35-e59b83ef3c22`,
	"transferStatus": `TransferStarted`,
	"transferAddress": `0xE37F80F22F43579EDCE961563F793031d00BFA9f `,
        "userActionDetails": {
            "pixCopyAndPaste": "loong-string-value"
        }      
}
```

**Comment by orlax** [comment]
Hey! so this way of doing things seems feasible. 

where would this user actions "userActionType" and "userActionDetails" schemas be defined? Would this just be compiled and added hardcoded to the specification? how would we go about defining then somewhere so that whoever does the PR has access to that information?

**Comment by cajubelt** [comment]
@orlax we're eager to hear what you think of Joe's PR here https://github.com/fiatconnect/specification/pull/97
